# OpenAPI ?? (JSON) ?? ??
springdoc.api-docs.enabled=true
# Swagger UI ??? ??
springdoc.swagger-ui.enabled=true
# ?? ?? ?? ??
springdoc.swagger-ui.display-request-duration=true
# API ?? ?? ?? ?? (list: ?? ??, none: ??)
springdoc.swagger-ui.doc-expansion=list
# ?? ?? ?? (alpha: ????)
springdoc.swagger-ui.tags-sorter=alpha
# HTTP ???(GET, POST ?) ??? ??
springdoc.swagger-ui.operations-sorter=method
# Swagger UI?? ?? ? ???? ?? ?? (???? ?????? ???)
springdoc.swagger-ui.persist-authorization=true
# ?? ?? ?? ?? (Swagger ?? ??? ??)
springdoc.default-produces-media-type=application/json
# ?? ?? ?? ??
springdoc.default-consumes-media-type=application/json
